init:
 - appveyor version
 - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
 - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
 - sh: lsb_release -d
 
test_script:
- sh: go version
- sh: |
    declare GO_VERSIONS=( "go1.7" "go1.8" "go1.9" "go1.10" "go1.11" "go1.12" "go1.13" )
    for v in "${GO_VERSIONS[@]}"; do
        gvm use ${v} ||
            { echo "[ERROR] Cannot use ${v}." 1>&2; exit 1; }
        go version
        if [[ $(go version) =~ ${v} ]]; then
            echo "Version is Correct"
        else
            echo "Version of go is incorrect!" 1>&2;
            exit 2;
        fi
    done

build: off
