test_script:
- sh: |
    declare GO_VERSIONS=( "go1.7" "go1.8" "go1.9" )
    for v in "${GO_VERSIONS[@]}"; do
        gvm use ${v} ||
            { echo "[ERROR] Cannot use ${v}." 1>&2; exit 1; }
        go version
        if [[ $(go version) =~ ${v} ]]; then
            echo "Version is Correct"
        else
            echo "Version of go is incorrect!" 1>&2;
            exit 2;
        fi
    done
build: off
